### ISSUE TITLE
Move to SQLite database

### ISSUE THREAD

**Issue by debloper** [debloper/SprintRPC#11]
A full-blown DB with basically a single necessary table is too much of a deployment hassle/dependency. Also, adding that information to the CONFIG/ENV file will mean downtime & needing to restart the app each time the info is updated.

A good middle ground is using SQLite for our purpose. Let's do it, @sudheesh001 :1234:

**Comment by sudheesh001** [comment]
On it !!

**Comment by sudheesh001** [comment]
Done. Good to close.

**Comment by debloper** [comment]
Thanks, well done!
