### ISSUE TITLE
Route to GET /bugs creates a type error and stops server

### ISSUE THREAD

**Issue by sudheesh001** [debloper/SprintRPC#30]
Traceback:
```
TypeError: Cannot read property 'bugs' of null
      at Request._callback ('.../bz.js');
      at Request.self.callback ('.../request.js');
      .
      .
      .
      at process._tickDomainCallback (node.js:413:13)
```
I think this is unwanted, we are not even using this, removing this from the route would be a better idea.

**Comment by debloper** [comment]
Well, `/bugs` is internally used as you can see in the last part of `app/js/services.js`
It expects the params to be provided, and if not then the server side controller finds null.
