### ISSUE TITLE
Remove stray traces of OAuth and fake json tests

### ISSUE THREAD

**Issue by sudheesh001** [debloper/SprintRPC#32]

**Comment by debloper** [comment]
Yeah, good to scrape them off.
Again, lower priority - comes after the multi-filter & URL parsing are done.

**Comment by sudheesh001** [comment]
But I patched this already :stuck_out_tongue_winking_eye: Review and merge :+1:

**Comment by debloper** [comment]
Heh, right... done! :grin:
