### ISSUE TITLE
Archived sprints section shows sprints that haven't finished yet.

### ISSUE THREAD

**Issue by sudheesh001** [debloper/SprintRPC#4]
STR:
1. Create a sprint for a future date.
2. Go to the Archived sprints section. You'll notice the sprint.
3. Click on the archive button in the sprint created.
4. Go back to Archived sprints section. You'll notice no difference.

A sprint is treated as completed even before its completion and shown with "date completed" though we are still behind the actual future date of completion.

**Comment by debloper** [comment]
@sudheesh001 commit message should have "fixes #4"
Anything inbetween breaks GH's NLP system :8ball:

**Comment by sudheesh001** [comment]
I'll keep that in mind from the next time.
