### ISSUE TITLE
Variable Parameterized list as URL encode/decode for generic querying in sprint

### ISSUE THREAD

**Issue by sudheesh001** [debloper/SprintRPC#42]
At the moment all the sprints have a few details only to search by, it'd be better to be able to have an extensible parameter list with the JSON Query

Do this issue before solving Issue #27

**Comment by debloper** [comment]
Fixed with https://github.com/debloper/SprintRPC/commit/8ac70a1a2cb73fb65880daf99965da2d38a0d953
